workflows:
  cordova_android_build:
    name: Build Cordova Android APK
    environment:
      vars:
        CORDOVA_PLATFORM: "android"
        ANDROID_HOME: /opt/android-sdk
        PATH: $PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
      node: 16.13.0 # Versão compatível do Node.js
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Install Cordova CLI
        script: npm install -g cordova

      - name: Accept Android Licenses
        script: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install dependencies
        script: npm install

      - name: Add Android platform
        script: cordova platform add android

      - name: Build APK
        script: cordova build android --release
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
